### ISSUE TITLE
shrimp plugin help

### ISSUE THREAD

**Issue by martin8smith** [AntonelloDN/ShrimpGIS#2] opened 2020-10-01 15:39 UTC
Hi Antonello,

Thank you for the help! The Read GEOJSON component seems to work fine with files that don't have a lot of data (i.e. datasets that just have polylines for city parks, or street center lines). But when I try to use .geojson files for building polygons and such, it seems to not like it and gives me that error. I can't really crop the .geojson file for just a specific area because A. I'm not sure how to do that (not a GIS wizard), and B. I really don't know what to crop yet (i'm using this for urban studies, so I would like to start analysis at a city scale)

Here's a screenshot showing the error: 

![2020-10-01T11_36_05](https://user-images.githubusercontent.com/52507869/94831187-6bb96c80-03da-11eb-9cd5-ba241f78e1bc.png)

And the .geojson file i'm trying to use:

https://we.tl/t-AlZ05PjZR3

Thanks Antonello!! I hope I can get this to work; your plugin seems amazing.

**Comment by AntonelloDN** [comment] 2020-10-02 17:42
Hi @martin8smith ,

Thanks for your kind words. Here is my debug:

pygeoj.py is an external module that I have integrated in ShrimpGIS: https://pypi.org/project/PyGeoj/

there is a problem with pygeoj.py when you have "geometry: null". Basically, there are some empty geometry in your geojson and pygeoj goes in error  (I need a double check but this is at the first look)
So you can run a raw script like this to remove all "geometry: null"

```
source = <ABSOLUTE PATH OF YOUR SOURCE FILE>
target = <ABSOLUTE PATH OF TARGET FILE>
to_search = '"geometry": null'

text = []
with open(source, 'r') as f:
    lines = f.readlines()
    for l in lines:
        if to_search in l:
            continue
        else:
            text.append(l)

with open(target, 'w') as f:
    for l in text:
        f.write(l)
```

There is a second problem, pygeo.py library supports only [X, Y] coordinates and not [X, Y, Z], like it is reported here: https://tools.ietf.org/html/rfc7946#section-3.1.7

So I have hacked the module in this simple way:
1. go to `%appdata%`
2. go to `shrimp_gis/io/pygeoj.py`
2. go to line 232 and add a third loop variable `_z` for example
![image](https://user-images.githubusercontent.com/16763953/94952459-53367880-04e6-11eb-8152-4a64c2a5d655.png)

... and this is the results. 
![image](https://user-images.githubusercontent.com/16763953/94952606-85e07100-04e6-11eb-9d6b-2493f2d973c1.png)
I think there are too many brep objects (218332) so Rhino will not run smoothly. If you need just few of them, you can trim the file with QGIS firstly. 

Contact me on Linkedin if you need the "clean" geojson.

Best,
Antonello

**Comment by martin8smith** [comment] 2020-10-06 12:39
Thanks a lot, Antonello! I will give this a try. I really need to learn QGIS to clip files... 

BTW, do you know if these building polygon shapes have the Z coordinates attached to them for building height values? That would be pretty intense information (I didn't think the city of Minneapolis even recorded all of that, but it could be a new thing).

**Comment by AntonelloDN** [comment] 2020-10-06 13:07
@martin8smith here is a possible method to crop a vector file.
![DVnNPRH0oT](https://user-images.githubusercontent.com/16763953/95204490-7746d200-07e4-11eb-9063-467337ec39d5.gif)
It seems that all z values are 0.0. Z value is used to set the height of the footprint on the terrain usually, whilst the height of the building should be part of the db, but that field seems to be missing
![image](https://user-images.githubusercontent.com/16763953/95204628-a52c1680-07e4-11eb-8c6a-95808bf9b2b6.png)
![image](https://user-images.githubusercontent.com/16763953/95205057-271c3f80-07e5-11eb-8b3f-1fb65ec0939b.png)

Best,
Antonello

**Comment by AntonelloDN** [comment] 2020-11-27 11:25
Hi @martin8smith I close this issue. I hope the explanation is clear.
So the problem is related to this standard RFC7946 and the PyGeoj library.

**Closed as completed by AntonelloDN** 2020-11-27 11:25 UTC
Labels: question
